# Copyright (c) The dgc.network
# SPDX-License-Identifier: Apache-2.0

name: grid_product
version: '1.0'
wasm: /tmp/grid-product-tp.wasm
inputs:
  - '621dee01'
  - '621dee02'
  - 'cad11d'
  - 'd39198'
  - 'd3919801'
  - 'd3919802'
outputs:
  - 'd39198'
  - 'd3919801'
  - '621dee02'
  - 'd3919802'
