# Copyright (c) The dgc.network
# SPDX-License-Identifier: Apache-2.0

name: grid_schema
version: '1.0'
wasm: /tmp/grid-schema-tp.wasm
inputs:
  - 'f350b8'
  - '621dee01'
  - 'cad11d'
outputs:
  - 'f350b8'
  - '621dee01'
  - 'ed02b300f28b89ad585d065f7d36a58023b5ce6e80985ffa0a776d801523debaa36446'
